vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    mappings:
        media:
            uri_prefix: '%media_storage_path_index%'
            upload_destination: default.storage.media
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y-m-d' # will create directory "2018/23/09" for curent date "2018-09-23"
                    date_time_property: createdAt # see above example
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true