vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        media:
            uri_prefix: '%media_storage_path_index%'
            upload_destination: '%kernel.project_dir%/%media_storage_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true